title: Sourish Shares
author: Sourish Kundu
email: sourishkundu07@gmail.com
description: >-
  Welcome to my blog! Here, I write about various topics about Computer Science, the industry in general, and about life too. If you have any thoughts, comments, or questions, please don't hesitate to reach out.
baseurl: "/blog"
url: "https://www.sourish.dev"
github_username:  sourish07
linkedin_username: sourish07
destination: ../blog
permalink: none
source: ../jekyll

# Google Analytics
google_analytics: 'G-Y9X7D11J18'

# Build settings
theme: minima
plugins:
  - jekyll-feed
