name: publish
on:
    workflow_dispatch:
    push:
        branches:
            - main
    pull_request:
        branches:
          - main
env:
    NODE_ENV: production
permissions:
    contents: read
    id-token: write
    pages: write
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 20
                  cache: "npm"
            - name: Setup .env
              run: |
                   echo NEXT_PUBLIC_GOOGLE_SHEETS_API_KEY=${{ secrets.GOOGLE_SHEETS_API_KEY }} >> .env.$NODE_ENV
                   echo NEXT_PUBLIC_GITHUB_BUILD=$GITHUB_REF_NAME >> .env.$NODE_ENV
            - name: Generate Main Website
              run: |
                  npm ci
                  npm run export
            - name: Cleanup Files
              run: |
                  shopt -s extglob
                  rm -rf !("out")
                  mv out/* .
                  rm -rf out
            - name: Archive build output
              run: |
                  cd ..
                  tar --dereference --hard-dereference --directory sourish07.github.io/ -cvf artifact.tar .
                  mv ./artifact.tar ./sourish07.github.io
            - name: Upload Artifact
              uses: actions/upload-artifact@main
              with:
                  name: github-pages
                  path: ./artifact.tar
                  if-no-files-found: warn
    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
