name: publish
on:
  push:
    branches:
      - main
permissions:
  contents: read
  id-token: write
  pages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Page with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./jekyll
          destination: ./blog
      - name: Archive build output
        run: |
          cd ..
          tar --dereference --hard-dereference --directory sourish07.github.io/ -cvf artifact.tar .
          mv ./artifact.tar ./sourish07.github.io
      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: github-pages
          path: ./artifact.tar
          if-no-files-found: warn
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
